const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = process.env.BELLWORKS_SCREENSHOTS || process.cwd() + '/screenshots';
(async () => {
  fs.mkdirSync(path,{recursive:true});
  const browser = await chromium.launch({headless:true});
  const context = await browser.newContext({viewport:{width:1440,height:1100},deviceScaleFactor:1});
  // Exercise the app deterministically; check-videos.cjs checks actual YouTube playback.
  await context.route('https://www.youtube-nocookie.com/embed/**',r=>r.fulfill({contentType:'text/html',body:'<html><body>Test player</body></html>'}));
  await context.route('https://www.youtube.com/iframe_api',r=>r.fulfill({contentType:'application/javascript',body:'window.YT={Player:function(frame,options){window.__videoEvents=options.events;this.destroy=function(){frame.remove();};setTimeout(function(){options.events.onReady();},0);}};window.onYouTubeIframeAPIReady();'}));
  const page = await context.newPage(); const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.BELLWORKS_URL || 'http://127.0.0.1:7331/bellworks.html');
  await page.evaluate(()=>document.fonts.ready);
  await page.waitForTimeout(700);
  await page.screenshot({path:path+'/desktop.png',fullPage:true});
  await page.getByRole('tab',{name:/Day B/}).click();
  assert.equal(await page.locator('#session-title').textContent(),'Pull & Hinge');
  await page.getByRole('button',{name:'View Gorilla Row',exact:true}).click();
  assert.equal(await page.locator('#studio-title').textContent(),'Gorilla Row');
  await page.locator('#map-back').click(); assert.equal(await page.locator('#map-back').getAttribute('aria-pressed'),'true');
  assert.equal(await page.locator('#studio-video').getAttribute('data-video-id'),'bLM3nLvoRdc');
  assert.equal(await page.locator('iframe').count(),0,'No unsolicited playback');
  await page.locator('#studio-video .video-poster').click();
  await page.locator('#studio-video iframe').waitFor();
  await page.evaluate(()=>window.__oldVideoEvents=window.__videoEvents);
  assert.match(await page.locator('#studio-video iframe').getAttribute('src'),/youtube-nocookie.com\/embed\/bLM3nLvoRdc/);
  assert.equal(await page.locator('#studio-video iframe').getAttribute('referrerpolicy'),'strict-origin-when-cross-origin');
  await page.locator('#open-exercise').click();
  assert.equal(await page.locator('#workout-title').textContent(),'Gorilla Row');
  await page.locator('#workout-weight').fill('16'); await page.locator('#workout-weight').blur();
  await page.locator('#log-set').click();
  assert.equal(await page.locator('#workout-set-count').textContent(),'1 / 3 completed');
  assert.equal(await page.locator('#rest-start').getAttribute('aria-label'),'Pause rest timer');
  await page.waitForTimeout(1100); assert.match(await page.locator('#rest-display').textContent(),/^1:2[7-9]$/);
  await page.locator('#rest-start').click(); const rest=await page.locator('#rest-display').textContent();
  await page.waitForTimeout(1100); assert.equal(await page.locator('#rest-display').textContent(),rest);
  await page.locator('#rest-reset').click(); assert.equal(await page.locator('#rest-display').textContent(),'1:30');
  await page.locator('#rest-skip').click(); assert.equal(await page.locator('#rest-display').textContent(),'Ready');
  assert.equal(await page.locator('#studio-video iframe').count(),0,'Opening workout stops the studio');
  await page.locator('#workout-video .video-poster').click(); await page.locator('#workout-video iframe').waitFor();
  await page.evaluate(()=>window.__oldVideoEvents.onStateChange({data:1}));
  assert.equal(await page.locator('#workout-video iframe').count(),1,'Late events from a retired player cannot stop the current video');
  await page.screenshot({path:path+'/workout.png'});
  await page.locator('#close-workout').focus(); await page.keyboard.press('Escape'); assert.equal(await page.locator('#workout-dialog').evaluate(d=>d.open),false);
  await page.waitForFunction(()=>!document.querySelector('iframe'));
  assert.equal(await page.locator('iframe').count(),0,'Closing workout destroys its player');
  await page.reload(); await page.waitForTimeout(300);
  assert.equal(await page.locator('#session-title').textContent(),'Pull & Hinge');
  await page.getByRole('button',{name:'View Gorilla Row',exact:true}).click(); await page.locator('#open-exercise').click();
  assert.equal(await page.locator('#workout-weight').inputValue(),'16');
  assert.equal(await page.locator('#workout-set-count').textContent(),'1 / 3 completed');
  await page.locator('#log-set').click(); await page.locator('#log-set').click();
  assert.equal(await page.locator('#workout-set-count').textContent(),'3 / 3 completed');
  await page.locator('#close-workout').click();
  assert.equal(await page.locator('#session-count').textContent(),'1 / 6 completed');
  await page.locator('#reset-session').click(); assert.equal(await page.locator('#session-count').textContent(),'0 / 6 completed');
  await page.locator('#toast-undo').click(); assert.equal(await page.locator('#session-count').textContent(),'1 / 6 completed');
  await page.locator('[data-nav="exercises"]').click();
  await page.locator('.library-card').first().waitFor();
  assert.equal(await page.locator('.library-card').count(),18);
  await page.locator('#exercise-search').fill('goblet'); assert.equal(await page.locator('.library-card').count(),2);
  await page.locator('#muscle-filter').selectOption('Back'); assert.equal(await page.locator('.library-card').count(),0);
  assert.equal(await page.locator('#library-empty').isVisible(),true);
  await page.locator('#clear-search').click(); assert.equal(await page.locator('.library-card').count(),18);
  await page.locator('#exercise-search').fill('renegade'); await page.locator('.library-open').click();
  assert.equal(await page.locator('#workout-title').textContent(),'Renegade Row');
  await page.locator('#close-workout').click(); await page.locator('#exercise-search').fill('');
  await page.screenshot({path:path+'/library.png',fullPage:true});
  await page.locator('[data-nav="progress"]').click();
  await page.locator('.progress-stat').first().waitFor();
  assert.match(await page.locator('#progress-stats').textContent(),/3/);
  assert.match(await page.locator('#training-log').textContent(),/16 kg/);
  await page.screenshot({path:path+'/progress.png',fullPage:true});
  await page.locator('[data-nav="guide"]').click(); await page.locator('#view-guide').waitFor(); assert.equal(await page.locator('#view-guide').isVisible(),true);
  await page.locator('[data-nav="training"]').click();
  await page.getByRole('tab',{name:/Day A/}).focus(); await page.keyboard.press('End');
  assert.equal(await page.locator('#session-title').textContent(),'Full Body');
  await page.keyboard.press('Home'); assert.equal(await page.locator('#session-title').textContent(),'Push & Squat');
  await page.locator('#warmup-toggle').click(); assert.equal(await page.locator('#warmup-content').isVisible(),true);
  await page.locator('#warmup-toggle').click();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.locator('#theme-toggle').click(); assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
  await page.waitForTimeout(100); await page.evaluate(()=>scrollTo({top:0,behavior:'instant'})); await page.screenshot({path:path+'/light.png',fullPage:true});
  await page.locator('#theme-toggle').click();
  for (const width of [1920,1280,1024,820,768,760,600,430,390,360,320]) {
    await page.setViewportSize({width,height:900}); await page.waitForTimeout(120);
    const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
    assert.equal(overflow,false,'Overflow at '+width);
  }
  await page.setViewportSize({width:390,height:844}); await page.waitForTimeout(300);
  await page.evaluate(()=>scrollTo({top:0,behavior:'instant'})); await page.screenshot({path:path+'/mobile.png',fullPage:true});
  await page.locator('#start-workout').click(); await page.waitForTimeout(400); await page.screenshot({path:path+'/mobile-workout.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.querySelector('#workout-dialog').scrollWidth <= document.querySelector('#workout-dialog').clientWidth),true);
  await page.keyboard.press('Escape');
  for (const view of ['exercises','progress','guide']) {
    await page.locator('[data-nav="'+view+'"]').click();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile overflow: '+view);
  }
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.locator('[data-nav="training"]').click();
  assert.equal(await page.locator('iframe').count(),0,'Reduced motion never starts video automatically');
  // Legacy storage migration: old exercise-level check implies every set is complete.
  await page.evaluate(()=>{localStorage.clear();localStorage.setItem('bw.done.a.goblet-squat','1');localStorage.setItem('bw.wt.a.goblet-squat','12');});
  await page.reload(); await page.locator('#open-exercise').click();
  assert.equal(await page.locator('#workout-set-count').textContent(),'3 / 3 completed');
  assert.equal(await page.locator('#workout-weight').inputValue(),'12');

  await page.locator('#close-workout').click();
  await page.setViewportSize({width:1440,height:1100});
  await page.locator('#studio-video .video-poster').click(); await page.locator('#studio-video iframe').waitFor();
  await page.evaluate(()=>window.__videoEvents.onError({data:101}));
  assert.match(await page.locator('#studio-video .video-status').textContent(),/can't|can’t play here/);
  const fallbackLink=await page.locator('#studio-video .video-external').getAttribute('href');
  assert.match(fallbackLink,/youtube.com\/watch\?v=/);
  await page.locator('[data-nav="exercises"]').click();
  await page.locator('#view-exercises').waitFor({state:'visible'});
  await page.waitForFunction(()=>!document.querySelector('iframe'));
  assert.equal(await page.locator('iframe').count(),0,'Navigation stops playback');
  await page.locator('.library-open').first().click();
  await page.locator('#workout-video .video-poster').click(); await page.locator('#workout-video iframe').waitFor();
  await page.locator('#next-exercise').click();
  assert.equal(await page.locator('iframe').count(),0,'Next movement stops playback');
  await page.locator('#close-workout').click();
  // API blocked: native iframe fallback and workout tracking remain available.
  const fallback = await browser.newContext({viewport:{width:390,height:844}});
  await fallback.route('https://www.youtube.com/iframe_api',r=>r.abort());
  await fallback.route('https://www.youtube-nocookie.com/embed/**',r=>r.fulfill({contentType:'text/html',body:'<html><body>Native YouTube fallback</body></html>'}));
  const fp=await fallback.newPage();
  fp.on('pageerror',e=>errors.push(e.message));
  await fp.goto(process.env.BELLWORKS_URL || 'http://127.0.0.1:7331/bellworks.html');
  await fp.locator('#studio-video .video-poster').click(); await fp.locator('#studio-video iframe').waitFor();
  await fp.locator('#open-exercise').click(); await fp.locator('#log-set').click();
  assert.equal(await fp.locator('#workout-set-count').textContent(),'1 / 3 completed');
  await fallback.close();
  assert.deepEqual(errors,[],'Browser exceptions');
  console.log('PASS: correct videos, playback lifecycle, error link, blocked API fallback, tabs/keyboard, anatomy, logging, rest timer, persistence, reset/undo, library filters, progress, guide, themes, 11 viewport widths, reduced motion, legacy data. No browser exceptions.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
